version: '3'
services:
  database:
    image: 'mysql:5.7'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
  backend:
    build: .
    ports:
    - 8000:80
    volumes:
    - ../:/var/www/